// Domains excluded from search results and extraction.
// Add any domain here to prevent it from ever entering the pipeline.
export const BLOCKED_DOMAINS: string[] = [
  'reddit.com',
  'instagram.com',
  'facebook.com',
  'twitter.com',
  'x.com',
  'youtube.com',
  'tiktok.com',
  'pinterest.com',
  'booksurfcamps.com',
  'tripadvisor.com',
  'yelp.com',
  'wikipedia.org',
  'wikipedia.com',
  'wikimedia.org',
  'windy.app',
  'kiterr.com',
  'thekitemag.com',
  'viator.com',
  'johnnyafrica.com',
  'wearecravingadventure.com',
  'wakeupstoked.com',
  'getyourguide.com',
  'kitereisen.tv',
  'kitetrip-planner.com',
  'globalkitespots.com',
  'retreat.guru',
  'iksurfmag.com',
];
